version: "3.9"
services:
  bot:
    build: .
    entrypoint: /opt/app/backend/docker-entrypoint.sh ${SERVER_PORT}
    environment:
      - TZ=${TZ}
      - REDDIT_SECRET=${REDDIT_SECRET}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - BOT_USER_AGENT="elbunuelo/Goalbot-1.0"
      - API_URL=${API_URL}
      - REDIS_URL=${REDIS_URL}
      - SERVER_PORT=${SERVER_PORT}
      - CREATE_DB=${CREATE_DB:-'false'}
      - DISABLE_DATABASE_ENVIRONMENT_CHECK=1
      - RAILS_ENV=${RAILS_ENV:-'production'}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - ./:/opt/app
    restart: unless-stopped
    env_file:
      - var.env
    depends_on:
      - redis
      - db
    labels:
      com.centurylinklabs.watchtower.enable: "false"
  video-finder:
    build: .
    entrypoint: /opt/app/backend/video-finder-entrypoint.sh
    environment:
      - TZ=${TZ}
      - REDDIT_SECRET=${REDDIT_SECRET}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - BOT_USER_AGENT="elbunuelo/Goalbot-1.0"
      - API_URL=${API_URL}
      - REDIS_URL=${REDIS_URL}
      - SERVER_PORT=${SERVER_PORT}
      - CREATE_DB=${CREATE_DB:-'false'}
      - DISABLE_DATABASE_ENVIRONMENT_CHECK=1
      - RAILS_ENV=${RAILS_ENV:-'production'}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - ./:/opt/app
    restart: unless-stopped
    env_file:
      - var.env
    depends_on:
      - bot
    labels:
      com.centurylinklabs.watchtower.enable: "false"
  telegram-client:
    build: .
    entrypoint: /opt/app/backend/telegram-client-entrypoint.sh
    environment:
      - TZ=${TZ}
      - REDDIT_SECRET=${REDDIT_SECRET}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - BOT_USER_AGENT="elbunuelo/Goalbot-1.0"
      - API_URL=${API_URL}
      - REDIS_URL=${REDIS_URL}
      - SERVER_PORT=${SERVER_PORT}
      - CREATE_DB=${CREATE_DB:-'false'}
      - DISABLE_DATABASE_ENVIRONMENT_CHECK=1
      - RAILS_ENV=${RAILS_ENV:-'production'}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - ./:/opt/app
    restart: unless-stopped
    env_file:
      - var.env
    depends_on:
      - bot
    labels:
      com.centurylinklabs.watchtower.enable: "false"
  resque:
    build: .
    entrypoint: /opt/app/backend/resque-entrypoint.sh
    environment:
      - TZ=${TZ}
      - REDDIT_SECRET=${REDDIT_SECRET}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - BOT_USER_AGENT="elbunuelo/Goalbot-1.0"
      - API_URL=${API_URL}
      - REDIS_URL=${REDIS_URL}
      - SERVER_PORT=${SERVER_PORT}
      - CREATE_DB=${CREATE_DB:-'false'}
      - DISABLE_DATABASE_ENVIRONMENT_CHECK=1
      - RAILS_ENV=${RAILS_ENV:-'production'}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - ./:/opt/app
    restart: unless-stopped
    env_file:
      - var.env
    depends_on:
      - redis
      - db
  resque-scheduler:
    build: .
    entrypoint: /opt/app/backend/scheduler-entrypoint.sh
    environment:
      - TZ=${TZ}
      - REDDIT_SECRET=${REDDIT_SECRET}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - BOT_USER_AGENT="elbunuelo/Goalbot-1.0"
      - API_URL=${API_URL}
      - REDIS_URL=${REDIS_URL}
      - SERVER_PORT=${SERVER_PORT}
      - CREATE_DB=${CREATE_DB:-'false'}
      - DISABLE_DATABASE_ENVIRONMENT_CHECK=1
      - RAILS_ENV=${RAILS_ENV:-'production'}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - ./:/opt/app
    restart: unless-stopped
    env_file:
      - var.env
    depends_on:
      - redis
      - db
    labels:
      com.centurylinklabs.watchtower.enable: "false"
  redis:
    image: redis
    command: redis-server
    volumes:
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - REDIS_REPLICATION_MODE=master
    env_file:
      - var.env
  db:
    image: postgres
    environment:
      - TZ=${TZ}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=goalbot_123
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=goalbot
    volumes:
      - ./postgres_data:/var/lib/postgresql
    restart: unless-stopped
    env_file:
      - var.env
